name: Deploy Web

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  web:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'development' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install deps
        run: yarn

      - name: Make .env
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_VITE_API_ENDPOINT: ${{ vars.API_ENDPOINT }}
          envkey_VITE_ADMIN_SUBSCRIPTION: ${{ vars.ADMIN_SUBSCRIPTION }}
          envkey_VITE_ADMIN_ENDPOINT: ${{ vars.ADMIN_ENDPOINT }}
          envkey_VITE_ENVIRONMENT: ${{ github.event.inputs.environment || 'development' }}
          envkey_VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          envkey_VITE_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          envkey_VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          envkey_VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
          envkey_VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          envkey_VITE_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          envkey_VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          envkey_VITE_REVENUECAT_API_KEY: ${{ secrets.REVENUECAT_API_KEY }}
          envkey_VITE_SENTRY_DNS: ${{ vars.SENTRY_DNS }}
          envkey_VITE_RUDDERSTACK_WRITE_KEY: ${{ vars.RUDDERSTACK_WRITE_KEY }}
          envkey_VITE_RUDDERSTACK_DATA_URL: ${{ vars.RUDDERSTACK_DATA_URL }}

      - name: Build app
        run: yarn build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          target: ${{ vars.FIREBASE_HOSTING_TARGET }}
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FABLED_976C8 }}
          channelId: ${{ vars.FIREBASE_CHANEL_ID }}
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
